<?php


namespace App\Http\Controllers\Api;


use App\Http\Controllers\Controller;

class userController extends Controller
{
    public function __call($method, $parameters)
    {
        parent::__call($method, $parameters); // TODO: Change the autogenerated stub
    }

    public function getIdentity(){
        $user_id =
    }

}